### ISSUE TITLE
Command "expo upload:ios" doesn't support selecting team id

### ISSUE THREAD

**Issue by ikhilko** [expo/expo-cli#182]
## Description

Apple ID can be presented in some teams (more that one). Currently there is no way to pass team id to "expo upload:ios" command.

## Expected Behavior

Should be possible to specify team id

## Observed Behavior

Right now it's failing with error

```
[21:23:29] Failed to upload the standalone app to the app store.
[21:23:29] Multiple Teams found; unable to choose, terminal not interactive!
```

## Environment

```
  Expo CLI 2.4.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.2 - ~/.nvm/versions/node/v9.11.2/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.11.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 31.0.4 => 31.0.4
      react: 16.5.0 => 16.5.0
      react-native: expo/react-native#sdk-31.0.0 => 0.57.1
      react-navigation: 3.0.0-rc.5 => 3.0.0-rc.5
```

**Comment by jakubste** [comment]
Fixed by #210

**Comment by metz0r** [comment]
@ikhilko does this work for you now? I still get this error in expo-cli@2.6.0. I use Application Loader for now.

**Comment by jakubste** [comment]
@metz0r what's your experience name?
you can also DM me at https://slack.expo.io/

**Comment by jakubste** [comment]
Turns out `FASTLANE_TEAM_ID` and `FASTLANE_ITC_TEAM_ID` is not the same. We're setting only the first one (and it's the only one we know).

Users can add the second one via an environment variable, but we should make it more obvious (probably also add a flag and better handling of error).

**Comment by ikhilko** [comment]
Now I cannot see an previous error about teamID, but still cannot use this command... I have MFA enabled for my developers account but there is no way to enter MFA key while trying to upload app.

**Comment by ikhilko** [comment]
Looks like it's an different issue, it should be possible to pass FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD env variable somehow...

**Comment by eapostol** [comment]
Hello @wkozyra95 . I still get this issue. what was the proper resolution for this? I am running expo-cli 
2.6.14. Thanks

**Comment by dsokal** [comment]
Hello @eapostol,
try upgrading `expo-cli`. 2.11.2 is the latest version - https://www.npmjs.com/package/expo-cli

**Comment by eapostol** [comment]
@dsokal will try to do so thanks - had an issue when upgrading to that version as well, ran npm i -g expo-cli a number of times now but still says I am running 2.6.14. No idea where that is.

> There is a new version of expo-cli available (2.11.2).
> You are currently using expo-cli 2.6.14
> Run `npm install -g expo-cli` to get the latest version
