### ISSUE TITLE
'gradlew' is not recognized after running 'expo eject'

### ISSUE THREAD

**Issue by rahamin1** [expo/expo-cli#397]
## Description

- I had an expo project that has been created by 'expo init' on windows 10, and was up and running
- I wanted to eject the project, and followed https://docs.expo.io/versions/latest/expokit/expokit/:
  --- executed `expo eject` and then `expo start`
  --- Then `cd android` and `gradlew installDevKernelDebug`
- I am getting the following error: `'gradlew' is not recognized as an internal or external command,
operable program or batch file.`

## Expected Behavior

I expected the instructions in https://docs.expo.io/versions/latest/expokit/expokit to work...

## Observed Behavior
See description above.

Note that in other projects on the same PC, that have been created without expo, using `react-native init`, `gradlew` is recognized inside the android folder of these projects.

## Environment

  Expo CLI 2.11.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.4 - C:\Users\yossi\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617

Emulator is genymotion version 3.0.0

**Comment by AdamJNavarro** [comment]
Hey @rahamin1,

Can you try creating and then ejecting a new project and see if you encounter the same issue running the `gradlew` command?

Cheers,
Adam

**Comment by rahamin1** [comment]
I did exactly that twice, in order to make sure that I followed the instructions.

**Comment by fson** [comment]
Looks like the difference between ExpoKit projects created with `expo eject` and projects created with `react-native init` is that the latter has a file named `gradlew.bat` in the `android/` folder of the project.

Could you try copying `android/gradlew.bat` from one of your other React Native projects (or from [GitHub](https://github.com/facebook/react-native/blob/92073770589abc68654e6f1abdd232b45241b181/template/android/gradlew.bat) to your ExpoKit project to see if that fixes the issue?

**Comment by rahamin1** [comment]
Done.

Here is what I get: when I run `gradlew installDevKernelDebug`

```
>gradlew installDevKernelDebug
Parallel execution with configuration on demand is an incubating feature.

> Configure project :app
Could not find google-services.json while looking in [src/prod/min/sdk/dev/kernel/debug, src/prod/min/sdk/dev/debug, src/prod/min/sdk/dev/kernel, src/prod/min/sdk/dev/kernelDebug, src/prod/min/sdk/debug, src/prod/min/sdk/dev, src/prod/min/sdk/devDebug, src/prod/min/debug, src/prod/min/sdk, src/prod/min/sdkDebug, src/prodMinSdkDevKernel/debug, src/debug/prodMinSdkDevKernel, src/prod/debug, src/prod/min, src/prod/minDebug, src/prodMinSdkDevKernel, src/debug, src/prodMinSdkDevKernelDebug, src/prod, src/prodDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/min/sdk/dev/kernel/release, src/prod/min/sdk/dev/release, src/prod/min/sdk/dev/kernel, src/prod/min/sdk/dev/kernelRelease, src/prod/min/sdk/release, src/prod/min/sdk/dev, src/prod/min/sdk/devRelease, src/prod/min/release, src/prod/min/sdk, src/prod/min/sdkRelease, src/prodMinSdkDevKernel/release, src/release/prodMinSdkDevKernel, src/prod/release, src/prod/min, src/prod/minRelease, src/prodMinSdkDevKernel, src/release, src/prodMinSdkDevKernelRelease, src/prod, src/prodRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/min/sdk/prod/kernel/debug, src/prod/min/sdk/prod/debug, src/prod/min/sdk/prod/kernel, src/prod/min/sdk/prod/kernelDebug, src/prod/min/sdk/debug, src/prod/min/sdk/prod, src/prod/min/sdk/prodDebug, src/prod/min/debug, src/prod/min/sdk, src/prod/min/sdkDebug, src/prodMinSdkProdKernel/debug, src/debug/prodMinSdkProdKernel, src/prod/debug, src/prod/min, src/prod/minDebug, src/prodMinSdkProdKernel, src/debug, src/prodMinSdkProdKernelDebug, src/prod, src/prodDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/min/sdk/prod/kernel/release, src/prod/min/sdk/prod/release, src/prod/min/sdk/prod/kernel, src/prod/min/sdk/prod/kernelRelease, src/prod/min/sdk/release, src/prod/min/sdk/prod, src/prod/min/sdk/prodRelease, src/prod/min/release, src/prod/min/sdk, src/prod/min/sdkRelease, src/prodMinSdkProdKernel/release, src/release/prodMinSdkProdKernel, src/prod/release, src/prod/min, src/prod/minRelease, src/prodMinSdkProdKernel, src/release, src/prodMinSdkProdKernelRelease, src/prod, src/prodRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/dev/kernel/debug, src/dev/min/sdk/dev/debug, src/dev/min/sdk/dev/kernel, src/dev/min/sdk/dev/kernelDebug, src/dev/min/sdk/debug, src/dev/min/sdk/dev, src/dev/min/sdk/devDebug, src/dev/min/debug, src/dev/min/sdk, src/dev/min/sdkDebug, src/devMinSdkDevKernel/debug, src/debug/devMinSdkDevKernel, src/dev/debug, src/dev/min, src/dev/minDebug, src/devMinSdkDevKernel, src/debug, src/devMinSdkDevKernelDebug, src/dev, src/devDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/dev/kernel/release, src/dev/min/sdk/dev/release, src/dev/min/sdk/dev/kernel, src/dev/min/sdk/dev/kernelRelease, src/dev/min/sdk/release, src/dev/min/sdk/dev, src/dev/min/sdk/devRelease, src/dev/min/release, src/dev/min/sdk, src/dev/min/sdkRelease, src/devMinSdkDevKernel/release, src/release/devMinSdkDevKernel, src/dev/release, src/dev/min, src/dev/minRelease, src/devMinSdkDevKernel, src/release, src/devMinSdkDevKernelRelease, src/dev, src/devRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/prod/kernel/debug, src/dev/min/sdk/prod/debug, src/dev/min/sdk/prod/kernel, src/dev/min/sdk/prod/kernelDebug, src/dev/min/sdk/debug, src/dev/min/sdk/prod, src/dev/min/sdk/prodDebug, src/dev/min/debug, src/dev/min/sdk, src/dev/min/sdkDebug, src/devMinSdkProdKernel/debug, src/debug/devMinSdkProdKernel, src/dev/debug, src/dev/min, src/dev/minDebug, src/devMinSdkProdKernel, src/debug, src/devMinSdkProdKernelDebug, src/dev, src/devDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/prod/kernel/release, src/dev/min/sdk/prod/release, src/dev/min/sdk/prod/kernel, src/dev/min/sdk/prod/kernelRelease, src/dev/min/sdk/release, src/dev/min/sdk/prod, src/dev/min/sdk/prodRelease, src/dev/min/release, src/dev/min/sdk, src/dev/min/sdkRelease, src/devMinSdkProdKernel/release, src/release/devMinSdkProdKernel, src/dev/release, src/dev/min, src/dev/minRelease, src/devMinSdkProdKernel, src/release, src/devMinSdkProdKernelRelease, src/dev, src/devRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)


FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDevKernelDebug' not found in root project 'android'.
```

**Comment by rahamin1** [comment]
After  getting the above messages, and since the project that I tried to eject was a project that I worked on for a while, and included dependencies that do not exist in a new expo project, I decided to try and eject a new project.

What I did:
- expo init test (I selected a project with tabs)
- cd test
- yarn 
- expo start (project built and is running on my genymotion emulator
- expo eject

I got the following prompt:
`What would you like your Android package name to be?`

I entered 'test' and got the following message:
`Invalid format of Android package name (only alphanumeric characters, '.' and
 '_' are allowed, and each '.' must be followed by a letter)`

**Comment by AdamJNavarro** [comment]
Hey @rahamin1,

Names for Android's Package property and iOS's BundleIdentifier need to use [reverse-DNS](https://en.wikipedia.org/wiki/Reverse_domain_name_notation) strings. You could use something like `com.rahamin1.test`

**Comment by rahamin1** [comment]
I did. This is my app.json:
```

{
  "expo": {
    "name": "Template",
    "description": "All the important information about my Pet",
    "slug": "template",
    "privacy": "public",
    "sdkVersion": "31.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "0.01",
    "orientation": "default",
    "icon": "./assets/images/icon.png",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.yossiglass.template",
      "splash": {
        "image": "./assets/images/splash-ios.png",
        "tabletImage": "./assets/images/splash-ios-tablet.png",
        "resizeMode": "cover",
        "backgroundColor": "#ffffff"
      }
    },
    "android": {
      "package": "com.yossiglass.template",
      "versionCode": 1,
      "permissions": [
        "CAMERA",
        "CAMERA_ROLL",
        "READ_INTERNAL_STORAGE",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ],
      "splash": {
        "ldpi": "./assets/images/splash.png",
        "mdpi": "./assets/images/splash.png",
        "hdpi": "./assets/images/splash.png",
        "xhdpi": "./assets/images/splash.png",
        "xxhdpi": "./assets/images/splash.png",
        "xxxhdpi": "./assets/images/splash.png",
        "tabletImage": "splash-android-tablet.png",
        "resizeMode": "cover",
        "backgroundColor": "#ffffff"
      },
      "icon": "./assets/images/icon.png",
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/icon-oreo.png",
        "backgroundColor": "#15b3bf"
      }
    }
  },
  "hooks": {
    "postPublish": [
      {
        "file": "sentry-expo/upload-sourcemaps",
        "config": {
          "organization": "self-dm",
          "project": "template",
          "authToken": "0ca29a9ed2e84e86bbac3e0e81b6e1ac208cf77f08ef48f9b28732d028e50cf6"
        }
      }
    ]
  }
}
```

**Comment by AdamJNavarro** [comment]
And you're still getting a prompt to enter Android's package name?

**Comment by rahamin1** [comment]
I got the prompt for package name only for this: https://github.com/expo/expo-cli/issues/397#issuecomment-467900025. This is, as mentioned in this post, a new project which I created and immediately ejected (without modifying app.json). 

All other posts discussed a project on which i worked for a while, where I specified the android package (as seen in the app.json file).

**Comment by stelmakhivan** [comment]
When I run from cmd console ` ./gradlew installDevKernelDebug` I get the error.
I tried to run it from git bash console and it works

**Comment by jkhales** [comment]
Closing as the issue seems resolved.
