### ISSUE TITLE
Cannot run npx expo run --offline

### ISSUE THREAD

**Issue by R4Y-repo** [expo/expo-cli#4573]
### Summary

So i want to check the performance of the app when it's offline for sign in/up form but for some reason the command gives this weird error
```
npx expo start --offline
Starting project at C:\Users\user\Documents\Github\project
FetchError: network timeout at: https://api.expo.dev/v2/versions/latest
FetchError: network timeout at: https://api.expo.dev/v2/versions/latest
    at Timeout.<anonymous> (C:\Users\user\Documents\Github\project\node_modules\node-fetch\lib\index.js:1484:13)
    at listOnTimeout (node:internal/timers:559:17)
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044        
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      babel-preset-expo: 9.2.0 => 9.2.0
      expo: 46.0.10 => 46.0.10
      metro: 0.70.3 => 0.70.3
      react: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

---

### Error output

```
npx expo start --offline
Starting project at C:\Users\rayen\Documents\Github\project
FetchError: network timeout at: https://api.expo.dev/v2/versions/latest
FetchError: network timeout at: https://api.expo.dev/v2/versions/latest
    at Timeout.<anonymous> (C:\Users\user\Documents\Github\project\node_modules\node-fetch\lib\index.js:1484:13)
    at listOnTimeout (node:internal/timers:559:17)
```

### Reproducible demo or steps to reproduce from a blank project

---

**Comment by EvanBacon** [comment]
Should be fixed in https://github.com/expo/expo/pull/19592/

**Comment by R4Y-repo** [comment]
So it's already fixed this week?

**Comment by R4Y-repo** [comment]
@EvanBacon any updates on how to use the offline feature correctly?

**Comment by OkancanCosar** [comment]
is it alive?
    "expo": "~46.0.13",
     "react": "18.0.0",
     "react-native": "0.69.6",

**Comment by emandres** [comment]
As of expo 48.0.6 this still appears to be broken. Getting the following error when running in offline mode:

`FetchError: network timeout at: https://api.expo.dev/v2/projects/{project-id}`
